# Generated by Django 2.0.3 on 2018-03-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foss',
            options={'verbose_name': 'foss', 'verbose_name_plural': 'foss'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'payment', 'verbose_name_plural': 'payment'},
        ),
        migrations.AlterModelOptions(
            name='tutorial_detail',
            options={'verbose_name': 'tutorial_detail', 'verbose_name_plural': 'tutorial_detail'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'user'},
        ),
    ]
