# Generated by Django 2.0.3 on 2018-03-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_web', '0002_auto_20180322_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial_detail',
            name='actual_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
