# Generated by Django 2.0.3 on 2018-03-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_web', '0003_auto_20180322_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial_detail',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
