# Generated by Django 2.0.3 on 2018-04-02 18:35

from django.db import migrations, models
import st_web.validator


class Migration(migrations.Migration):

    dependencies = [
        ('st_web', '0007_auto_20180402_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial_detail',
            name='expected_date',
            field=models.DateField(validators=[st_web.validator.validate_date]),
        ),
        migrations.AlterField(
            model_name='tutorial_detail',
            name='tutorial',
            field=models.FileField(upload_to='documents/', validators=[st_web.validator.validate_file_extension]),
        ),
    ]
